name: Schedule Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  scheduled_demo:
    runs-on: ubuntu-latest

    steps:
      - name: Log time
        run: |
          current_date_time = $(date)
          echo "Current Data and Time: $current_date_time"
