name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps: 
      - name: set output
        id: set-output
        run: |
          echo "name=shyam" >> $GITHUB_OUTPUT
          echo "age=23" >> $GITHUB_OUTPUT

      - name: set output
        id: set-output2
        run: |
          echo "salary=36000" >> $GITHUB_OUTPUT
  
      - name: access output
        run: |
          echo "The value of the output name is ${{ steps.set-output.outputs.name }}"
          echo "The value of the output age is ${{ steps.set-output.outputs.age }}"
          echo "The value of the output salary is ${{ steps.set-output2.outputs.salary }}"
