name: Step Output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    - name: set output
      id: set-output
      run: echo "age=23" >> $GITHUB_OUTPUT

    - name: access output
      run: echo ${{ steps.set-output.outputs.age }}
